# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a032dbbf4d2b93299d0c9394b1f96f37168b45c7a652149509afc258f982db4bff2f368d989f1d75d320d85b164d0f4f3dcdde46253066ca7365fef0a21c0a9

test:
  secret_key_base: 246fd5a0ac791a1becbefd7efb6ad21e3a929621a19840646de493c88bc731e2c59825241798e3608e95348afd8d1fe6889d57bd784b3178098e0d11bd8590bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
